[package]
name = "raplay"
version = "0.5.1"
edition = "2024"
license = "GPL-3.0"
description = "Library for playing audio"
homepage = "https://github.com/BonnyAD9/raplay"
repository = "https://github.com/BonnyAD9/raplay"
readme = "README.md"
keywords = ["audio"]
categories = ["multimedia::audio"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.104"
cpal = "0.18.2"
dasp_sample = "0.11.0"
num = "0.4.3"
serde = { version = "1.0.229", features = ["std", "derive"], optional = true }
symphonia = { version = "0.6.1", features = ["all"] }
thiserror = "2.0.20"

[features]
default = []
serde = ["dep:serde"]
