[package]
name = "raplay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.15.2"
eyre = "0.6.8"
symphonia = "0.5.3"
